### ISSUE TITLE
North Minish Hole in Lake Hylia + Minish Woods North Minish Hole Show as requiring Flute

### ISSUE THREAD

**Issue by Alaszun** [cubesolver111/TMCMapTracker#78]
I assume this is coming from the sequence breaking with flute, but it seems to hard lock the check right now in your logic.

![image](https://user-images.githubusercontent.com/27381189/73909349-51d28480-4861-11ea-9995-d5ca209203ce.png)

![image](https://user-images.githubusercontent.com/27381189/73909344-4d0dd080-4861-11ea-97f0-7236a03da123.png)

**Comment by cubesolver111** [comment]
Definitely coded the sequence break incorrectly, my bad
