### ISSUE TITLE
Lon Lon Key + Cane should unlock goron quest

### ISSUE THREAD

**Issue by Alaszun** [cubesolver111/TMCMapTracker#80]
A bit of a cursed logic sequence, but it's possible to get to Goron Quest via the Lon Lon Key and Cane. This doesn't show up as in logic.

![image](https://user-images.githubusercontent.com/27381189/74056136-40d75f80-4996-11ea-832a-87c13a79bab8.png)

![image](https://user-images.githubusercontent.com/27381189/74056142-4634aa00-4996-11ea-866a-c683213e9ea4.png)

**Comment by Alaszun** [comment]
Btw cube, if you'd like me to do this in another format (discord message, etc) rather than this, let me know. Just figured it'd be easier to do it on the github itself.

**Comment by cubesolver111** [comment]
Thanks for catching that
